services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bdmaria
      MYSQL_USER: adminmaria
      MYSQL_PASSWORD: passmaria
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
